export class id_codes {
  static idCode = {
    user: "US",
    eventCategory: "EC",
    customerSupport: "CS",
    landingPageDetails: "LPD",
    event: "EV",
    userEvent: "UEV",
    blog: "BL",
    blogComment: "BLC",
    subscription: "SUB",
    guestTicket: "GT",
    advert: "AD",
    advertRegion: "ADR",
    advertLanguage: "ADL",
    advertDailyBudget: "ADB",
    advertCallToAction: "ADCTA",
    advertPlacementPrice: "ADPP",
    notification: "NOT",
    userAppNotification: "UAN",
    product: "PR",
    userCart: "UC",
    userPurchasesHistory: "UPH",
    eventHostRating: "EHR",
    eventReport: "ER",
  };
}
