export class languageContent {
  static profile = {
    English: {
      title: "Profile",
      editHobbies: "Edit Hobbies",
      following: "Following",
      followers: "Followers",
      GoldStatus: "Gold Status",
      settings: "Settings",
      notifications: "Notifications",
      paymentSubscriptions: "Payment & Subscriptions",
      security: "Security",
      contact: "Contact",
      guidelines: "Guidelines",
      refererFriend: "Refer a Friend",
      termsConditions: "Terms & Conditions",
      nightMode: "Night Mode",
      deleteAccount: "Delete Account",
      signOut: "Sign Out",
    },
    French: {
      title: "Profil",
      editHobbies: "Modifier les loisirs",
      following: "Abonnements",
      followers: "Abonnés",
      GoldStatus: "Statut Or",
      settings: "Paramètres",
      notifications: "Notifications",
      paymentSubscriptions: "Paiements & Abonnements",
      security: "Sécurité",
      contact: "Contact",
      guidelines: "Directives",
      refererFriend: "Parrainer un ami",
      termsConditions: "Termes & Conditions",
      nightMode: "Mode Nuit",
      deleteAccount: "Supprimer le compte",
      signOut: "Se déconnecter",
    },
    Spanish: {
      title: "Perfil",
      editHobbies: "Editar pasatiempos",
      following: "Siguiendo",
      followers: "Seguidores",
      GoldStatus: "Estado Oro",
      settings: "Configuraciones",
      notifications: "Notificaciones",
      paymentSubscriptions: "Pagos y Suscripciones",
      security: "Seguridad",
      contact: "Contacto",
      guidelines: "Pautas",
      refererFriend: "Referir a un amigo",
      termsConditions: "Términos y Condiciones",
      nightMode: "Modo Nocturno",
      deleteAccount: "Eliminar Cuenta",
      signOut: "Cerrar sesión",
    },
    German: {
      title: "Profil",
      editHobbies: "Hobbys bearbeiten",
      following: "Folgend",
      followers: "Anhänger",
      GoldStatus: "Goldstatus",
      settings: "Einstellungen",
      notifications: "Benachrichtigungen",
      paymentSubscriptions: "Zahlungen & Abonnements",
      security: "Sicherheit",
      contact: "Kontakt",
      guidelines: "Richtlinien",
      refererFriend: "Einen Freund werben",
      termsConditions: "Geschäftsbedingungen",
      nightMode: "Nachtmodus",
      deleteAccount: "Konto löschen",
      signOut: "Abmelden",
    },
    Chinese: {
      title: "个人资料",
      editHobbies: "编辑爱好",
      following: "关注",
      followers: "粉丝",
      GoldStatus: "黄金状态",
      settings: "设置",
      notifications: "通知",
      paymentSubscriptions: "付款和订阅",
      security: "安全",
      contact: "联系",
      guidelines: "指南",
      refererFriend: "推荐朋友",
      termsConditions: "条款和条件",
      nightMode: "夜间模式",
      deleteAccount: "删除账户",
      signOut: "登出",
    },
    Arabic: {
      title: "الملف الشخصي",
      editHobbies: "تعديل الهوايات",
      following: "المتابَعون",
      followers: "المتابِعون",
      GoldStatus: "الحالة الذهبية",
      settings: "الإعدادات",
      notifications: "الإشعارات",
      paymentSubscriptions: "المدفوعات والاشتراكات",
      security: "الأمان",
      contact: "اتصل",
      guidelines: "الإرشادات",
      refererFriend: "أحِل صديقًا",
      termsConditions: "الشروط والأحكام",
      nightMode: "الوضع الليلي",
      deleteAccount: "حذف الحساب",
      signOut: "تسجيل الخروج",
    },
  };
}
